SimpleRPG/SimpleRPGMVC_Reboot/Controllers/BattleController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleRPG;
using SimpleRPG.MonsterFactory;
using System;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using SimpleRPG.Tools;

namespace SimpleRPGMVC.Controllers
{
    using Model;

    public class BattleController : Controller
    {
        private readonly EnemyFactory enemyFactory = new EnemyFactory();

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Initialize()
        {
            var session = HttpContext.Session;
            var battleFromSession = retrieveBattleFromSession(session);
            var player = battleFromSession.player;
            var enemy = battleFromSession.enemy;
            GenerateNewPlayerOrEnemyIfNeeded(ref player, ref enemy);
            var battleToString = SerializeBattle(player, enemy);
            updateEntitiesInSession(battleToString, session);
            return Content(battleToString);
        }

        [HttpGet]
        public IActionResult Attack()
        {
            var session = HttpContext.Session;
            var BattleFromSession = retrieveBattleFromSession(session);
            var player = BattleFromSession.player;
            var enemy = BattleFromSession.enemy;
            return getViewFromOutcome(player, enemy, session);
        }

        private void GenerateNewPlayerOrEnemyIfNeeded(ref Player player, ref Enemy enemy)
        {
            if (player == null || player.IsDead)
            {
                player = new Player();
                enemy = enemyFactory.MakeEnemy("rodent");
            }
            if (enemy == null || enemy.IsDead)
            {
                enemy = enemyFactory.MakeEnemy("rodent");
            }
        }

        private SerializedBattle retrieveBattleFromSession(ISession session)
        {
            var str = session.GetString("battle");
            if (str == null)
            {
                return new SerializedBattle();
            }
            return JsonConvert.DeserializeObject<SerializedBattle>(str);
        }

        private IActionResult getViewFromOutcome(Player player, Enemy enemy, ISession session)
        {
            player.RegularAttack(enemy);
            var battle = SerializeBattle(player, enemy);
            updateEntitiesInSession(battle, session);
            if (player.IsDead)
            {
                return PartialView("Gameover");
            }
            if (enemy.IsDead)
            {
                return PartialView("Victory");
            }

            return Content(battle, "application/json");
        }

        private ISession updateEntitiesInSession(String serializedBattle, ISession session)
        {
            session.SetString("battle", serializedBattle);
            return session;
        }

        private String SerializeBattle(Player player, Enemy enemy)
        {
            var log = Battlelog.getLogAndClear();
            var serializedBattle = new SerializedBattle()
            {
                player = player,
                enemy = enemy,
                log = log
            };
            return JsonConvert.SerializeObject(serializedBattle);
        }
    }
}

SimpleRPG/SimpleRPGMVC_Reboot/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SimpleRPGMVC_Reboot.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

SimpleRPG/SimpleRPGMVC_Reboot/Views/Battle/Gameover.cshtml
@model Battle

@using SimpleRPG

@{
    ViewData["Title"] = "Index";
}
@section battle {
    <link href="~/css/battle.css" rel="stylesheet" type="text/css"/>
}

<div id="flex_container">
    <div id="battle_stats">
        <h3>You are dead.</h3>
    </div>
</div>

SimpleRPG/SimpleRPGMVC_Reboot/Views/Battle/Index.cshtml
@model Battle

@using SimpleRPG

@{
    ViewData["Title"] = "Index";
}
@section battle {
    <link href="~/css/battle.css" rel="stylesheet" type="text/css" />
}
<div id="main_container">
    <div id="flex_container">
        <div id="battle_stats">
            <h3>Battle commencing!</h3>
            Battle over: <span id="battle_isOver"></span>
        </div>
        <div id="battle_contestants">
            <div class="stats">
                <h4 id="player_name"></h4>
                <ul>
                    <li>HP: <span id="player_life"></span></li>
                    <li>Mana: <span id="player_mana"></span></li>
                    <li>Stamina: <span id="player_stamina"></span></li>
                    <li>Experience: <span id="player_experience"></span></li>
                </ul>
            </div>
            <div class="stats">
                <h4 id="enemy_name">Monster</h4>
                <ul>
                    <li>HP: <span id="enemy_life"></span></li>
                    <li>Mana: <span id="enemy_mana"></span></li>
                    <li>Stamina: <span id="enemy_stamina"></span></li>
                </ul>
            </div>
        </div>
        <div id="battle_log_container">
            <h4>Battle log</h4>
            <textarea id="battlelog_display" readonly></textarea>
        </div>
        <div id="control_panel">
            <input id="attack" type="button" value="Attack!" />
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript" src="@Url.Content("js/entity.js")"></script>
    <script type="text/javascript" src="@Url.Content("js/player.js")"></script>
    <script type="text/javascript" src="@Url.Content("js/enemy.js")"></script>
    <script type="text/javascript" src="@Url.Content("js/battle.js")"></script>
    <script type="text/javascript" src="@Url.Content("js/game.js")"></script>
    <script>
        $(document).ready(function () {
            initializeBattle();
        });
    </script>
}

SimpleRPG/SimpleRPGMVC_Reboot/Views/Battle/Victory.cshtml
    <div id="flex_container">
        <div id="battle_stats">
            <h3>Victory!</h3>
        </div>
    </div>

SimpleRPG/SimpleRPGMVC_Reboot/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SimpleRPG/SimpleRPGMVC_Reboot/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SimpleRPG/SimpleRPGMVC_Reboot/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

SimpleRPG/SimpleRPGMVC_Reboot/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SimpleRPGMVC_Reboot</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
    @RenderSection("battle", required: false)
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SimpleRPGMVC_Reboot</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Battle" asp-action="Index">Battle</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2017 - SimpleRPGMVC_Reboot</p>
    </footer>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>